Name:           ros-hydro-strands-engagement-checker
Version:        0.0.1
Release:        0%{?dist}
Summary:        ROS strands_engagement_checker package

Group:          Development/Libraries
License:        MIT
URL:            https://github.com/strands-project/activity_analysis
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-bayes-people-tracker
Requires:       ros-hydro-rospy
Requires:       ros-hydro-std-msgs
BuildRequires:  ros-hydro-bayes-people-tracker
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-rospy
BuildRequires:  ros-hydro-std-msgs

%description
The engagement_checker package

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Wed Oct 29 2014 Mohannad Al Omari <omari.1988@gmail.com> - 0.0.1-0
- Autogenerated by Bloom

